// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNHqFMUQjN-tui_EmbfcCgiQu_oKCxEKM',
    appId: '1:411847394283:web:a4cf85d856aa07999f8fae',
    messagingSenderId: '411847394283',
    projectId: 'strata-mini',
    authDomain: 'strata-mini.firebaseapp.com',
    storageBucket: 'strata-mini.firebasestorage.app',
    measurementId: 'G-VZYECC0K6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC1_8_5mcv7uvk_TKaZ_I-IEk-GaVusgc',
    appId: '1:411847394283:android:d155d2f5b7ee95ea9f8fae',
    messagingSenderId: '411847394283',
    projectId: 'strata-mini',
    storageBucket: 'strata-mini.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSkBvvUOrsgn9s1owHOIsJgLJjEhia8nc',
    appId: '1:411847394283:ios:03188c88d583876c9f8fae',
    messagingSenderId: '411847394283',
    projectId: 'strata-mini',
    storageBucket: 'strata-mini.firebasestorage.app',
    iosBundleId: 'com.example.projekStrataMini',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNHqFMUQjN-tui_EmbfcCgiQu_oKCxEKM',
    appId: '1:411847394283:web:392c9c96da723e3a9f8fae',
    messagingSenderId: '411847394283',
    projectId: 'strata-mini',
    authDomain: 'strata-mini.firebaseapp.com',
    storageBucket: 'strata-mini.firebasestorage.app',
    measurementId: 'G-2V0TMHCK8X',
  );
}
