# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_install_all_pods
  require_relative File.join(File.dirname(__FILE__), 'Flutter', 'podhelper.rb')
end

target 'Runner' do
  flutter_install_all_pods
end